name: nf-core-madman-1.1dev
channels:
  - maxibor
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - adapterremoval
  - bcftools
  - bowtie2
  - damageprofiler
  - fastp
  - fastqc
  - graphviz
  - markdown
  - megahit
  - multiqc
  - numpy
  - pandas
  - pip
  - pmdtools
  - prodigal
  - prokka
  - python
  - quast
  - rich
  - samtools
  - spades
  - spectra
  - tqdm
  - pymdown-extensions
  - pydamage