name: megahit-nf-0.1-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - adapterremoval
  - fastqc
  - samtools
  - pmdtools
  - damageprofiler
  - bowtie2
  - megahit
  - quast
  - prokka
  - multiqc
  - click
  - numpy
  - pandas
  - pip
  - pysam
  - python>=3.6
  - scipy
  - statsmodels
  - pip:
    - git+https://github.com/maxibor/pydamage.git
