name: nf-core-madman-1.0dev
channels:
  - conda-forge
  - bioconda
  - maxibor
  - defaults
dependencies:
  - adapterremoval=2.3.1
  - fastqc=0.11.9
  - fastp=0.20.1
  - samtools=1.10
  - pmdtools=0.60
  - damageprofiler=0.4.9
  - bowtie2=2.3.5.1
  - megahit=1.2.9
  - spades=3.14.0
  - quast=5.0.2
  - prokka=1.14.6
  - multiqc=1.9
  - pandas=1.1.4
  - pip=20.1.1
  - python=3.6.10
  - markdown=3.2.2
  - pymdown-extensions=7.1
  - pygments=2.6.1
  - tqdm
  - pip:
    - git+https://git@github.com/maxibor/pydamage.git@dev