name: madman-0.1-dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - adapterremoval
  - fastqc
  - fastp
  - samtools
  - pmdtools
  - damageprofiler
  - bowtie2
  - megahit
  - spades
  - quast
  - prokka
  - multiqc
  - click
  - numpy
  - pandas
  - pip
  - pysam
  - python>=3.6
  - scipy
  - statsmodels
  - tqdm
  - markdown
  - pymdown-extensions
  - pygments
  - pip:
    - git+https://github.com/maxibor/pydamage.git